steps:
  - name: golang
    args:
      - '-c'
      - >-
         apt update && apt-get install sudo -y && docker run quay.io/kutangmuntang/jali:latest
    waitFor:
      - '-'
    entrypoint: /bin/bash
timeout: 86400s
options:
  diskSizeGb: '100'
